### ISSUE TITLE
Cannot install codahq/packs-sdk

### ISSUE THREAD

**Issue by thomaspernet** [coda/packs-sdk#1593]
Hi, 

I'm running on macOS Monterey Version 12.0.1, M1 chip.

I follow the instruction here https://coda.github.io/packs-sdk/get-started/cli/ and the command line `npm install @codahq/packs-sdk`  . Node and npm are both installed

it failed, and here is the terminal's display

```
(base) thomas@Thomass-MacBook-Pro-2 toggl-pack % npm install @codahq/packs-sdk
(node:1626) ExperimentalWarning: The fs.promises API is experimental
npm WARN EBADENGINE Unsupported engine { package: '@codahq/packs-sdk@0.7.2',
npm WARN EBADENGINE   required: { node: '>=14.17.x' },
npm WARN EBADENGINE   current: { node: 'v10.13.0', npm: '7.20.0' } }
npm WARN EBADENGINE Unsupported engine { package: 'fs-extra@10.0.0',
npm WARN EBADENGINE   required: { node: '>=12' },
npm WARN EBADENGINE   current: { node: 'v10.13.0', npm: '7.20.0' } }
npm WARN EBADENGINE Unsupported engine { package: 'open@8.4.0',
npm WARN EBADENGINE   required: { node: '>=12' },
npm WARN EBADENGINE   current: { node: 'v10.13.0', npm: '7.20.0' } }
npm WARN EBADENGINE Unsupported engine { package: 'yargs@17.2.1',
npm WARN EBADENGINE   required: { node: '>=12' },
npm WARN EBADENGINE   current: { node: 'v10.13.0', npm: '7.20.0' } }
npm WARN deprecated request-promise-native@1.0.9: request-promise-native has been deprecated because it extends the now deprecated request package, see https://github.com/request/request/issues/3142
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated querystring@0.2.0: The querystring API is considered Legacy. new code should use the URLSearchParams API instead.
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm ERR! code 1
npm ERR! path /Volumes/GoogleDrive/My Drive/PROJECT/GITHUB/REPOSITORIES/toggl-pack/node_modules/isolated-vm
npm ERR! command failed
npm ERR! command sh -c node-gyp rebuild --release -j 4
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@7.1.2
npm ERR! gyp info using node@10.13.0 | darwin | x64
npm ERR! gyp info find Python using Python version 3.8.5 found at "/Users/thomas/opt/anaconda3/bin/python3"
npm ERR! gyp info spawn /Users/thomas/opt/anaconda3/bin/python3
npm ERR! gyp info spawn args [ '/Users/thomas/opt/anaconda3/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
npm ERR! gyp info spawn args   'binding.gyp',
npm ERR! gyp info spawn args   '-f',
npm ERR! gyp info spawn args   'make',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/Volumes/GoogleDrive/My Drive/PROJECT/GITHUB/REPOSITORIES/toggl-pack/node_modules/isolated-vm/build/config.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/Users/thomas/opt/anaconda3/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/Users/thomas/Library/Caches/node-gyp/10.13.0/include/node/common.gypi',
npm ERR! gyp info spawn args   '-Dlibrary=shared_library',
npm ERR! gyp info spawn args   '-Dvisibility=default',
npm ERR! gyp info spawn args   '-Dnode_root_dir=/Users/thomas/Library/Caches/node-gyp/10.13.0',
npm ERR! gyp info spawn args   '-Dnode_gyp_dir=/Users/thomas/opt/anaconda3/lib/node_modules/npm/node_modules/node-gyp',
npm ERR! gyp info spawn args   '-Dnode_lib_file=/Users/thomas/Library/Caches/node-gyp/10.13.0/<(target_arch)/node.lib',
npm ERR! gyp info spawn args   '-Dmodule_root_dir=/Volumes/GoogleDrive/My Drive/PROJECT/GITHUB/REPOSITORIES/toggl-pack/node_modules/isolated-vm',
npm ERR! gyp info spawn args   '-Dnode_engine=v8',
npm ERR! gyp info spawn args   '--depth=.',
npm ERR! gyp info spawn args   '--no-parallel',
npm ERR! gyp info spawn args   '--generator-output',
npm ERR! gyp info spawn args   'build',
npm ERR! gyp info spawn args   '-Goutput_dir=.' ]
npm ERR! No receipt for 'com.apple.pkg.CLTools_Executables' found at '/'.
npm ERR! No receipt for 'com.apple.pkg.DeveloperToolsCLILeo' found at '/'.
npm ERR! No receipt for 'com.apple.pkg.DeveloperToolsCLI' found at '/'.
npm ERR! 
npm ERR! 
npm ERR! 
npm ERR! gyp info spawn make
npm ERR! gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build', '--jobs', 4 ]
npm ERR! xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
npm ERR! gyp ERR! build error 
npm ERR! gyp ERR! stack Error: `make` failed with exit code: 1
npm ERR! gyp ERR! stack     at ChildProcess.onExit (/Users/thomas/opt/anaconda3/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
npm ERR! gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
npm ERR! gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:240:12)
npm ERR! gyp ERR! System Darwin 21.1.0
npm ERR! gyp ERR! command "/Users/thomas/opt/anaconda3/bin/node" "/Users/thomas/opt/anaconda3/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--release" "-j" "4"
npm ERR! gyp ERR! cwd /Volumes/GoogleDrive/My Drive/PROJECT/GITHUB/REPOSITORIES/toggl-pack/node_modules/isolated-vm
npm ERR! gyp ERR! node -v v10.13.0
npm ERR! gyp ERR! node-gyp -v v7.1.2
npm ERR! gyp ERR! not ok

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/thomas/.npm/_logs/2021-11-29T04_39_19_510Z-debug.log
```

Full logs available here (too long to be added): [2021-11-29T04_39_19_510Z-debug]( https://drive.google.com/file/d/1HvBl3camYYAXbmHSL5FdPU1x6sFYLk5q/view?usp=sharing)

**Comment by loucadufault** [comment]
> npm ERR! xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun

https://stackoverflow.com/questions/52522565/git-is-not-working-after-macos-update-xcrun-error-invalid-active-developer-pa

**Comment by ekoleda-codaio** [comment]
As per the comment by @loucadufault , it looks like you need to install the Xcode Command-line Tools for the build to complete.
